# And what they died from: cause-specific mortality in England at the district level {#sec-Chapter6}

## Overview

## Methods

I performed a high-­resolution spatiotemporal analysis of civil registration data in which I extracted de­-identified data for all deaths in England from 2002 to 2019 (8,648,191 death records, extract date: 17<sup>th</sup> November 2022).
England was divided into 314 districts according to the boundaries in 2020.
Deaths were assigned into the following age groups: $0, 1–4, 5–9, ..., 80–84, 85+$ years.
I did not use 130 death records (<0.001%) for which sex was not recorded.
There were no age­-district-­year combinations in which the number of deaths from all causes exceeded population.

Each death record in the post-neonatal period was assigned an ICD-10 code corresponding to the underlying cause of death.
For neonates, which are not assigned an underlying cause of death, I used the ICD-10 code in the first position on the death record.
I used ICD-10 codes to assign each death to 136 cause groups of the WHO Global Health Estimates (GHE) study [@WHOMethodsData2020]; these groups encompass causes of death with related aetiology and clinical and public health relevance.
I also grouped diabetes mellitus and nephritis and nephrosis (hereafter referred to as _diabetes_) as these deaths might have a similar history.
I used the top 12 causes of death according to the total number of deaths from 2002 to 2019 for cause-specific analysis, as well as a residual groups comprising deaths from all other cancers, all other NCD, all other CVD, all other infections, maternal, perinatal and nutritional conditions (IMPN), and injuries (external causes).
Together, these form a mutually exclusive, collectively exhaustive list of causes of death.

The full list of ICD-10 codes for each cause group can be found in @tbl-ap-ch6-causes.

Although the size of the spatial unit of analysis has been increased to the district-level, by stratifying by cause of death, the number of death in each age-district-year-cause stratum is still very small.
As in @sec-Chapter4 and @sec-Chapter5, I used a Bayesian hierarchical model to obtain stable estimates of death rates.
I conducted all analyses separately by sex and cause group.

I used a binomial likelihood:
$$
\text{deaths}_{ast} = \text{Binomial}(m_{ast}, \text{Population}_{ast}).
$$ {#eq-ch-6-likelihood}
A beta-binomial was trialled but did not improve model fit.
The model is as follows:
$$
\text{logit}({m_{ast}}) = \alpha_0 + \beta_0 t + \alpha_{1s} + \beta_{1s} t + \alpha_{2a} + \beta_{2a} t + \xi_{as} + \gamma_{at},
$$ {#eq-ch-6-model}
where the terms have the same meanings as @eq-ch-4-model.
This is the same as model @sec-Chapter5, but without a random walk for each spatial unit, which was tested but did not improve the fit despite adding a lot of complexity.

Spatial effects were modelled using a ICAR effect rather than the nested hierarchy of random effects seen in @sec-Chapter4 and @sec-Chapter5.
The geographies here only allow a two-tier hierarchy with only nine regions mapping to 314 districts, which was less preferable than a spatial model.

All model parameters, their priors and dimensions are in @tbl-ap-ch6-model.

I fitted the model in the probabilistic programming language NumPyro [@phanComposableEffectsFlexible2019] and obtained 1,000 draws from the posterior distribution of model parameters that were used to calculate age-specific death rates.
Where possible, non-centred parameterisations were used in the model to improve the efficiency of the NUTS samplers.
I ran four chains with a warmup of 2000 iterations and then 10,000 further iterations and thinned the remainder by 40 to obtain 1000 post-burn-in draws from the posterior distribution of model parameters.

I ran a model for a combined group of all deaths to calculate life expectancy in each district.
Death rates for this total mortality group, and for injuries, were corrected in 2017 in Kensington and Chelsea for the Grenfell fire by imputing using the mean deaths from injuries between 2016 and 2018 before running the model.

The primary reporting outcome is the unconditional probability of dying between birth and 80 years of age.
Unconditional probability is the probability of death in the absence of competing causes of death, and is calculated using life table methods from age-specific death rates from the cause of interest.
I limited the age range to 80 years because the probability of death in the absence of competing causes equals 100% when the entire life course is considered.
The reported 95% credible intervals represent the 2.5<sup>th</sup> and 97.5<sup>th</sup> percentiles of the posterior distribution of estimated probability of death.

I calculated the contributions of deaths from each cause of death, in each age group, to the life expectancy change for each district between different time periods using Arriaga's method, which is widely used to decompose life expectancy differences between populations or population subgroups [@arriagaMeasuringExplainingChange1984].
Arriaga's method calculates how much each age group contributes to the life expectancy difference by summing how much death rate differences at that age change the years of life lived both at that age and in subsequent ages through changing the number of survivors.
It then partitions the age-specific contributions to the life expectancy gap by cause of death in proportion to the difference in cause-specific death rates between the subgroups.
The cause-specific death rates were scaled such that the sum over all causes was equal to the estimate for total mortality.
For this analysis, I used the sample mean death rate in each age-district-year-cause combination.

Details on the calculations for both the probability of dying and Arriaga's method can be found in @sec-appA.

## Results

### All causes

There were 4,465,948 (48.4%) deaths in women and 4,182,108 (51.6%) in men in England from 2002 to 2019.
<!-- 1,533,703 (62.5%) of these deaths occurred in people aged younger than 80 years of age. -->
@fig-ch-6-treemap shows the leading causes of death for each sex.

![Total number of deaths for the 12 leading causes of death in England from 2002 to 2019, and the residual groups all other cancers, all other NCD, all other CVD, all other infections, maternal, perinatal and nutritional conditions (IMPN), and injuries. The boxes are coloured by the wider groups of CVDs; NCDs; cancers; materal, perinatal, nutritional and infectious causes; injuries. See @tbl-ap-ch6-causes for ICD-10 codes for each category. ^[For brevity, the group "diabetes mellitus, nephritis and nephrosis" has been shortened to "diabetes".]](../thesis-analysis/thesis_analysis/causes/figures/treemap.pdf){#fig-ch-6-treemap}

In the following sections, I will write in turn on each of the wider cause groups (CVDs; NCDs; cancers; materal, perinatal, nutritional and infectious causes; injuries) in order of largest proportion of total deaths.

### Cardiovascular diseases

2,712,895 (31.4%)

### Non-communicable diseases

2,508,844 (29.0%)

### Cancers

2,464,500

Cancers accounted for 28.5% of all deaths

With over 150 different types of cancer, each with their own anatomical and molecular subtypes, cancer is extremely complex, with specialist workforce for dedicated to each unique cancer.
Compared with CVDs and NCDs, which are dominated by their major causes (IHD and stroke, and Alzheimer's, COPD and diabetes, respectively), cancers have the largest number of individual causes in the top 12.
I felt I should go deeper into the cancer story, and pay further attention to more site-specific cancers.
This is the focus of @sec-Chapter7.

### Materal, perinatal, nutritional and infectious causes

666,783 (7.7)

### Injuries

295,034 (3.4)

### Contribution to life expectancy change

## Discussion

Comparison to Bennett 2018
Comparison to GBD 2015
What is causing the epi transition backward that we saw at the MSOA level

Skew towards older ages, due to how we chose the groups on number of deaths, which itself is skewed towards older ages

Migration not as much of an issue
Today it remains the case that the majority of moves occur over short distances: the 2011 Census records that 57.1% of the individuals aged 16 and over that changed address within the preceding 12 months moved within the same Local Authority District (LAD).

## Summary
