# Discussion {#sec-Chapter8}

## Public health and policy implications of findings

Although previous studies have observed a decline in female life expectancy in the bottom two deciles of deprivation in the past decade [@bennettContributionsDiseasesInjuries2018; @marmotMarmotReview102020], this thesis has shown both for men and women where the declines have been happening for small areas.
Not only have there been declines, but the declines have been accelerating in the latter half of the decade, such that in the period 2014-19, life expectancy fell 1 in 5 MSOAs for women and 1 in 9 for men.
These trends happened in the years before the mortality-forcing event of the Covid-19 pandemic and are worse than comparable countries [@leonTrendsLifeExpectancy2019], and should be deemed a failure for public health policy.
Although the complexity of policy means it cannot be proved casually, leaders within the NHS have pointed towards constrained funding for the healthcare body itself, as well as cuts to wider social determinants, such as housing and education, as the main reason for the country's poor performance [@hamRiseDeclineNHS2023].

The declines in life expectancy were sustained over a long period of time, which serves as another example where death rates for some population subgroups run contrary to the persistent mortality decline of the third stage of the Epidemiologic Transition theory, as discussed in @gaylinRefocusingLensEpidemiologic1997 with the HIV/AIDS pandemic.
And even if England is in the hypothesised fourth stage of the transition, the Age of Delayed Degenerative diseases [@olshanskyFourthStageEpidemiologic1986], there are subnational patterns where degenerative diseases are *not* killing at later and later ages.
The difference in progress between districts in the last decade was largely driven by differences in these degenerative diseases.
In particular, the rate of improvement for CVD and all other NCDs, and the strength of the negative forcing effect of Alzheimer's and other dementias.
Furthermore, female mortality from infectious, maternal, perinatal and nutritional conditions (GBD group 1), which dominate the second stage of the transition, increased in many districts.
There is also worrying shift towards injuries (GBD group 3) contributing negatively towards life expectancy progress, particularly for men.
This is possibly driven by a rise in "deaths of despair" [@angusIncreasesDeathsDespair2023; @caseRisingMorbidityMortality2015], although this would require further analysis by stratifying into intentional and unintentional injuries.
It should be noted that IMPN and injuries do not play a major role in total mortality as they accounted for only 11.1% of all deaths from 2002 to 2019, but they are almost entirely preventable and should be addressed through appropriate policy.

Cancer outcomes in the UK are worse than those in Europe in general [@oecdOECDReviewsHealth2016].
In this thesis, I found mortality showed huge spatial variation for a number of preventable cancers.
Worryingly, at the same level of poverty, London performed significantly better that the rest of the country for several cancers.
This suggests either regional differences in the quality of care, or differences in the populations living in deprived areas, which should both be the subject for policy discussions.

Finally, this thesis emphasises the value of small area work in informing policy.
National trends in mortality are not spatially homogenous.
Particular diseases have shown massive variation at the district level, such as COPD in women (6.0-fold in 2019), and by studying England at the MSOA level, I have uncovered the widest subnational gap in life expectancy of 27.0 years (men in 2019) in the literature.
This rich source of data allows policy makers to work with local authorities to create targeted public health interventions.
The population issues at the LSOA level in London and the coding of CVD on the Isle of Wight show there are still limitations of the data.
Nevertheless, the estimates from this thesis are already being used in the press to provide context for recent falls in US life expectancy [@burn-murdochWhyAreAmericans2023], and I hope they are also being discussed by policymakers.

## Future work

There are many possible substantive and methodological extensions to the work presented in this thesis.
Firstly, on the substantive side, there is a reason the final year of study period was restricted at 2019 that has nothing to do with the availability of civil registration data for the proceeding years: the Covid-19 pandemic.
It would be naïve to fit the same model to an extended time period that includes the pandemic years because the pandemic had such a major influence on mortality patterns.
The model relies heavily on linear trends, which would be affected by the final years.
Further, pandemics are fat-tailed events, so the _Gaussian_ random walk effects would struggle to capture the shock without increasing the overall variance of the effect. 

Rather than extending the study to include the pandemic years and look at the trends between 2002 and 2023, a more interesting question is "had the pandemic _not_ happened, how would mortality patterns be different?"
This would be done using a counterfactual analysis: train a model to estimate annual mortality from 2002 to 2019 and produce a forecast for the years from 2020.
A team, including myself, has already done this analysis at the national level at a weekly temporal resolution [@kontisMagnitudeDemographicsDynamics2020; @kontisLessonsLearnedLessons2022].
Here, the task would instead involve forecasts for each sex-age-space-time-cause stratum on annual timescales.
The group has been involved in a number of mortality forecasting projects [@kontisFutureLifeExpectancy2017; @bennettFutureLifeExpectancy2015; @foremanSmallAreaForecasts2017].
The models are similar to those in this thesis, but would need to be adapted and trained specifically for forecasting purposes, with the possibility of averaging multiple models to reduce bias.
The results would allow us to see how the cause-composition of mortality has changed compared to the _business as usual_ scenario.
We would obviously expect and increase in deaths infectious disease, but were injuries reduced as the country was locked down in their homes?
Did cancer outcomes worsen due to missed surgeries as hospitals were flooded with Covid-19 patients?
Is there a longer term effect due to strain on emergency services, which has manifested in longer waiting lists and waiting times for appointments [@dorlingHowAusterityCaused2023]?
And, how have these effects varied for different age groups and different areas of the country?

Improvements in hardware and inference methods, such as variational inference rather than sampling
In theory, with improvements both to hardware and the rise of approximate inference algorithms to replace computationally costly sampling methods, the models can be scaled to higher and higher spatial resolutions and we could potentially estimate mortality for the entire country for LSOAs, OAs, or even postcodes.
However, given the data issues in @sec-Chapter5, perhaps bigger is not better when the quality of the data is lacking.

One of the major strengths of the thesis was the use of Bayesian methods, at one of the highest spatial resolutions in the literature for a model estimating mortality.
This was largely thanks to recent developments in probabilistic programming, which allow sampling to run on GPUs rather than CPUs, and is generally faster for models with over 10,000 parameters [@laoTfpMcmcModern2020].
The models themselves, which were based on previous work in the group [@bennettFutureLifeExpectancy2015; @bennettContributionsDiseasesInjuries2018], followed traditional statistical approaches using intercepts and linear slopes and adding in random walk effects for non-linearities.
However, with models such as @eq-ch-4-model, we are actually only interested in the left-hand side of the equation – the death rate – and not at all in the values of the parameters on the right-hand side.
There are a vast array of flexible models which can describe complex data without needing to design heavily parametrised structures.
These range from Gaussian processes [@rasmussenGaussianProcessesMachine2006; @flaxmanFastHierarchicalGaussian], where the user can use inductive biases and their own knowledge to influence how the model fits the data, to wilder options like neural networks, which completely sacrifice any remaining interpretability of the effects.

During my PhD, I became very familiar with the literature on Gaussian processes, and was involved with a paper aimed at speeding up inference in spatial settings [@semenovaPriorVAEEncodingSpatial2022].
One of the most promising avenues for the task of mortality estimation in this thesis, outlined in @flaxmanFastHierarchicalGaussian, is the use of Kronecker-structured covariance matrices to create hierarchical Gaussian processes.
In there context of this thesis, the covariance matrix would be defined as the Kronecker product of three smaller matrices: one for age effects, one for spatial effects, and one for temporal effects.
We can exploit the Kronecker structure for faster inference, as we no longer need to invert the full matrix (an operation that scales cubically with the number of data points), but rather the smaller constituent matrices of each effect.
Ultimately, nothing came to fruition as the working environment due to the sensitivity of the data ^[Working on a cluster with no internet access and only a command line interface – good luck installing your favourite packages. This is why spatial statisticians only study Scottish lip cancer.] was not conducive to developing novel statistical methods.
Also, there was no guarantee the Gaussian process methods would be quicker, as it still requires the inversion of a large spatial matrix, nor would it produce a result much different from the original model.
Instead, I allocated time to scaling existing models and testing new hardware.
I believe the hierarchical Gaussian process model should be the starting point for future research because it is much more flexible and requires less testing of each effect than the models in this thesis.

Another methodological extension would be to model causes of death jointly, thereby borrowing strength across _causes_.
Diseases often share common risk factors and similar aetiologies, so there often is some redundancy in specifying a unique spatial surface for each cause.
In the disease mapping literature, studies have built spatial models which share spatial components between diseases.
Firstly, @knorr-heldSharedComponentModel2001 considered a model (also described in @bestComparisonBayesianSpatial2005) for two diseases, with disease-specific spatial components and one shared component.
@heldJointDiseaseMapping2005 generalised this approach to model any number of diseases as a weighted sum of shared components.
Rather than a general approach, both @downingJointDiseaseMapping2008 and @mahakiJointSpatiotemporalShared2018 allocated the spatial components to the diseases _a priori_ based on knowledge of the common risk factors between cancers such as smoking, obesity and alcohol consumption.
@foremanSmallAreaForecasts2017 allowed for more variability by modelling interactions between each spatial unit and cause.
There is also the option to extend the hierarchical Gaussian process described above with another component covariance matrix describing the correlations between each of the cause groups.
Ultimately, the goal would be to run a single joint model that flexibly describes interactions between sexes, age groups, spatial units, time, and causes of death.

<!-- ## Conclusions -->
