project:
  type: book
  output-dir: _thesis/

book:
  title: Spatiotemporal modelling of all-cause and cause-specific mortality in England
  author:
    name: Theo Alexander Omar Rashid
    url: https://theorashid.github.io/
  # cover-image: thesis-analysis/thesis_analysis/eda/figures/age_mx_void.webp
  favicon: assets/favicon.png
  # downloads: [pdf]
  abstract: |
    High-resolution data for changes in mortality and longevity are scarce.
    Estimating mortality for specific combinations of spatial units, time periods, age groups, and causes of death poses statistical and computational challenges which typically result in compromises in the granularity of the results.
    I applied Bayesian hierarchical models based on patterns of mortality over age, space, and time, to obtain robust yearly estimates of life expectancy and cause-specific mortality for small areas.
    Using vital registration data held by the UK Small Area Health Statistics Unit, I investigated trends in mortality for subnational units in England from 2002 to 2019.

    I examined trends in life expectancy in England's 6791 middle-layer super output areas (MSOAs).
    In the years 2014-19, 1270 (18.7%) MSOAs for women and 784 (11.5%) MSOAs for men saw declines in life expectancy.
    The same analysis was performed for the 4835 lower-layer super output areas which comprise London.
    At this smaller level, issues with the population data in the older age groups affected the reliability of the life expectancy estimates.

    I modelled cause-specific mortality for 314 districts in England.
    The inequality in life expectancy increase since 2010 was driven largely by that of deaths from dementias and the residual group of non-communicable diseases, as well as ischaemic heart disease in men.
    The analysis was extended to look specifically at the top ten leading cancer causes of death.
    Preventable cancers showed the greatest spatial inequality in 2019.
    Unlike areas in the rest of the country, mortality in London from several cancers did not increase in poorer districts, suggesting that some features of London weaken the relationship between poverty and mortality.

    England has seen increasing inequalities in all-cause mortality over the past two decades, driven by rises in mortality for a large number of communities and from several preventable causes of death.
  chapters:
    - index.qmd
    - Chapters/Chapter2.qmd
    - Chapters/Chapter3.qmd
    - Chapters/Chapter4.qmd
    - Chapters/Chapter5.qmd
    - Chapters/Chapter6.qmd
    - Chapters/Chapter7.qmd
    - Chapters/Chapter8.qmd
    - Chapters/Chapter9.qmd
    - references.qmd
  appendices:
    - Appendices/AppendixA.qmd
    - Appendices/AppendixB.qmd
    - Appendices/AppendixC.qmd
    - Appendices/AppendixD.qmd
    - Appendices/AppendixE.qmd

  site-url: https://theorashid.github.io/thesis
  repo-url: https://github.com/theorashid/thesis
  repo-actions: [issue]
  search: false

thesis:
  supervisor:
    name: Majid Ezzati, James E Bennett, Seth Flaxman
  degree-name: Doctor of Philosophy (PhD)
  university: Imperial College London
  department: Department of Epidemiology and Biostatistics
  group: School of Public Health
  faculty: School of Public Health
  copyright: "Frontmatter/copyright.tex"
  declaration: "Frontmatter/declaration.tex"
  # quotation:
  #   text: "Nobody is going to read your thesis."
  #   attribution: Kyle Foreman
  acknowledgements: "Frontmatter/acknowledgements.tex"
  abbreviations: "Frontmatter/abbreviations.tex"

bibliography: [thesis.bib]
csl: "elife.csl"

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf:
    urlcolor: blue
    linkcolor: blue
    toclinkcolor: black
    toc-depth: 3
    cover-image: "assets/imperial.pdf"
  docx:
    toc: true
    toc-depth: 3
    always_allow_html: true
  html:
    theme: [cosmo, assets/theme.scss]
    toc: true
    toc-depth: 3

